# Generated by Django 5.2.13 on 2026-04-27 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_marche', models.CharField(blank=True, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('categorie', models.CharField(choices=[('Travaux', 'Travaux'), ('Fournitures', 'Fournitures'), ('Services', 'Services'), ('Études', 'Études')], max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('bientot', 'Bientôt expiré'), ('expire', 'Expiré')], default='actif', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='marches/pdf/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='soumissions/pdf/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('soumis_le', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to=settings.AUTH_USER_MODEL)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='authentication.marche')),
            ],
            options={
                'ordering': ['-soumis_le'],
                'unique_together': {('marche', 'fournisseur')},
            },
        ),
    ]
