# Generated by Django 5.2.13 on 2026-07-13 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='date_debut',
            field=models.DateField(default=datetime.date(2026, 7, 13)),
            preserve_default=False,
        ),
    ]
